theme: jekyll-theme-minimal
title: inWebStyle Solutions
description: Administration, mises à jour, soutien technique, conception et refonte de sites web. Administration, updates, technical support, and [re]design of websites. <A HREF="mailto:inwebstyle@gmail.com">Contact</A>
logo: /assets/img/iws-logo.png
